export type QBittorrentTorrentState =
	| 'allocating'
	| 'checkingDL'
	| 'checkingResumeData'
	| 'checkingUP'
	| 'downloading'
	| 'error'
	| 'forcedDL'
	| 'forcedUP'
	| 'metaDL'
	| 'missingFiles'
	| 'moving'
	| 'pausedDL'
	| 'pausedUP'
	| 'queuedDL'
	| 'queuedUP'
	| 'stalledDL'
	| 'stalledUP'
	| 'stoppedDL'
	| 'stoppedUP'
	| 'unknown'
	| 'uploading'

export type QBittorrentTorrentStateOption = QBittorrentTorrentState | 'all' | 'active'
