import type { ColumnOption } from '@/types/ColumnOption'

export const TORRENT_TABLE_COLUMNS: ColumnOption[] = [
	{
		uid: 'normalized_priority',
		name: 'PRIORITY',
		description: 'torrent priority in the queue',
		sortable: true,
		width: 10,
		hideHeader: true,
	},
	{
		uid: 'state',
		name: 'STATE',
		description: 'torrent current state',
		sortable: true,
		width: 10,
		hideHeader: true,
	},
	{
		uid: 'name',
		name: 'NAME',
		description: 'torrent name',
		sortable: true,
		width: '100%',
	},

	{
		uid: 'dlspeed',
		name: 'SPEED DL',
		description: 'the current download speed of the torrent',
		sortable: true,
		width: 120,
	},
	{
		uid: 'downloaded',
		name: 'TOTAL DL',
		description: 'total amount downloaded for the torrent',
		sortable: true,
		width: 120,
	},
	{
		uid: 'downloaded_session',
		name: 'SESS. DL',
		description: 'total amount download for the torrent during the current session',
		sortable: true,
		width: 120,
	},
	{
		uid: 'upspeed',
		name: 'SPEED UP',
		description: 'torrent current upload speed',
		sortable: true,
		width: 120,
	},
	{
		uid: 'uploaded',
		name: 'TOTAL UP',
		description: 'total amount uploaded for the torrent',
		sortable: true,
		width: 120,
	},
	{
		uid: 'uploaded_session',
		name: 'SESS. UP',
		description: 'total amount uploaded for the torrent during the current session',
		sortable: true,
		width: 120,
	},

	{
		uid: 'completed',
		name: 'COMPLETED',
		description: 'total amount of data considered completed for the torrent',
		sortable: true,
		width: 120,
	},
	{
		uid: 'total_size',
		name: 'SIZE',
		description: 'torrent total size',
		sortable: true,
		width: 120,
	},

	{
		uid: 'num_seeds',
		name: 'SEEDS',
		description: 'number of connected seeder for the torrent',
		sortable: true,
		width: 120,
	},
	{
		uid: 'num_leechs',
		name: 'LEECHS',
		description: 'number of connected peers for the torrent',
		sortable: true,
		width: 120,
	},

	{
		uid: 'availability',
		name: 'AVAIL.',
		description: 'torrent availability',
		sortable: true,
		width: 120,
	},
	{
		uid: 'popularity',
		name: 'POPUL.',
		description: 'torrent popularity (ratio/time active)',
		sortable: true,
		width: 120,
	},
	{
		uid: 'ratio',
		name: 'RATIO',
		description: 'torrent current seed ratio (uploaded/downloaded)',
		sortable: true,
		width: 120,
	},
	{
		uid: 'ratio_limit',
		name: 'RATIO L.',
		description: 'torrent ratio seeding limit',
		sortable: true,
		width: 120,
	},
	{
		uid: 'max_ratio',
		name: 'RATIO M.',
		description: 'torrent max ratio',
		sortable: true,
		width: 120,
	},

	{
		uid: 'category',
		name: 'CATEGORY',
		description: 'torrent category',
		sortable: true,
		width: 120,
	},
	{
		uid: 'tags',
		name: 'TAGS',
		description: 'torrent tags',
		sortable: true,
		width: 120,
	},

	{
		uid: 'eta',
		name: 'ETA',
		description: 'torrent estimated remaining download time',
		sortable: true,
		width: 120,
	},
	{
		uid: 'progress',
		name: 'PROGRESS',
		description: 'torrent current progress in %',
		sortable: true,
		width: 120,
	},

	{
		uid: 'completion_on',
		name: 'COMPLETED',
		description: 'torrent completion date',
		sortable: true,
		width: 200,
	},
	{
		uid: 'added_on',
		name: 'ADDED',
		description: 'torrent added date',
		sortable: true,
		width: 200,
	},
	{
		uid: 'tracker',
		name: 'TRACKER',
		description: 'torrent tracker name',
		sortable: true,
		width: 80,
		hideHeader: true,
	},
	{
		uid: 'hash',
		name: 'HASH',
		description: 'torrent hash',
		sortable: true,
	},
]
