name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.9.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Create tar.gz archive
        run: tar -czvf qwb-${{ github.ref_name }}.tar.gz -C ./dist .

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release create "$TAG" -t "Release $TAG" --notes-from-tag qwb-${{ github.ref_name }}.tar.gz
